# Generated by Django 5.2.8 on 2025-11-28 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_km', models.IntegerField(blank=True, null=True)),
                ('total_drive_time_minutes', models.IntegerField(blank=True, null=True)),
                ('total_break_time_minutes', models.IntegerField(blank=True, null=True)),
                ('total_rest_time_minutes', models.IntegerField(blank=True, null=True)),
                ('total_other_work_time_minutes', models.IntegerField(blank=True, null=True)),
                ('admin_time_minutes', models.IntegerField(blank=True, null=True)),
                ('schedule', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carrier')),
                ('driver_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calc_driver_1', to='drivers.driver')),
                ('driver_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calc_driver_2', to='drivers.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_number', models.IntegerField()),
                ('stop_type', models.CharField(choices=[('START_FROM_BASE', 'Start from base'), ('LOADING', 'Loading'), ('UNLOADING', 'Unloading'), ('PARTIAL_LOADING', 'Partial loading'), ('PARTIAL_UNLOADING', 'Partial unloading'), ('FINAL_STOP', 'Final stop'), ('RETURN_TO_BASE', 'Return to base')], max_length=30)),
                ('location', models.CharField(max_length=150)),
                ('driver_participates', models.BooleanField(default=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='transport.route')),
            ],
            options={
                'ordering': ['stop_number'],
            },
        ),
        migrations.CreateModel(
            name='TransportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loading_place', models.CharField(max_length=150)),
                ('unloading_place', models.CharField(max_length=150)),
                ('distance_km', models.PositiveIntegerField(default=0)),
                ('price_for_customer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('carrier_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.carrier')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customer')),
                ('driver_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_driver', to='drivers.driver')),
                ('driver_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_driver', to='drivers.driver')),
            ],
        ),
    ]
